[Project1/손호민] Notion 클로닝 프로젝트
prgrms-fe-devcourse/FEDC5-5_Project_Notion_VanillaJS pull request #21
Opened 2023-10-26 13:02 UTC by HoberMin

배포링크 : https://notion-clone-project-nine.vercel.app/

## 📌 과제 설명
바닐라 JS만을 이용해 노션을 클로닝합니다.

## 👩‍💻 요구 사항과 구현 내용
- [x] 글 단위를 Document라고 합니다. Document는 Document 여러개를 포함할 수 있습니다.
- [x] 화면 좌측에 Root Documents를 불러오는 API를 통해 루트 Documents를 렌더링합니다.
  - [x] Root Document를 클릭하면 오른쪽 편집기 영역에 해당 Document의 Content를 렌더링합니다.
  - [x] 해당 Root Document에 하위 Document가 있는 경우, 해당 Document 아래에 트리 형태로 렌더링 합니다.
  - [x] Document Tree에서 각 Document 우측에는 + 버튼이 있습니다. 해당 버튼을 클릭하면, 클릭한 Document의 하위 Document로 새 Document를 생성하고 편집화면으로 넘깁니다.
- [x] 편집기에는 기본적으로 저장 버튼이 없습니다. Document Save API를 이용해 지속적으로 서버에 저장되도록 합니다.
- [x] History API를 이용해 SPA 형태로 만듭니다.
  - [x] 루트 URL 접속 시엔 별다른 편집기 선택이 안 된 상태입니다.
  - [x] /documents/{documentId} 로 접속시, 해당 Document 의 content를 불러와 편집기에 로딩합니다.

## 보너스 요구사항
- [ ] 기본적으로 편집기는 textarea 기반으로 단순한 텍스트 편집기로 시작하되, 여력이 되면 div와 contentEditable을 조합해서 좀 더 Rich한 에디터를 만들어봅니다.

- [ ] 편집기 최하단에는 현재 편집 중인 Document의 하위 Document 링크를 렌더링하도록 추가합니다.

- [ ] 편집기 내에서 다른 Document name을 적은 경우, 자동으로 해당 Document의 편집 페이지로 이동하는 링크를 거는 기능을 추가합니다.

- [ ] 그외 개선하거나 구현했으면 좋겠다는 부분이 있으면 적극적으로 구현해봅니다!

## ✅ 간단 회고
> 프로젝트를 진행하면서 처음에 어떻게 시작해야 할지 감이 오지않았고, 간단하게 설계를 하고 시작했습니다. 설계과정이 있었음에도 불구하고 Documents의 리스트조차 렌더링이 잘 되지 않아서 몇일을 갈아엎는 과정이 반복되었는데, 해당 과정이 있어서였는지 모르겠지만 늦게나마 진행되기 시작했고 만족스럽진 않지만 기본 요구사항은 모두 충족할 수 있는 단계까지 되었다고 생각합니다. 보너스 요구사항 및 부족한 부분들은 꾸준히 수정해나갈 예정입니다.

## ✅ 궁금한 점
- 각 컴포넌트별 상태관리를 어떻게 하는게 옳은지
- 개발을 진행하면서 소위말해 1도 모르는 CSS를 굉장히 많이 사용했는데 CSS없이 기능할 수 있도록 수정할 예정입니다.
  - 예시 : `display : none` 등등
- 컴포넌트간의 상호작용을 어떻게 하는지 잘 모르겠습니다.
   > 예를들어 Editor에서 텍스트를 수정하는데 렌더링없이 List가 수정된다던지, Header에서 렌더링없이 텍스트가 변화하는 등 
- `contentEditable`을 조합해 구현하는 방법을 익혀야 하는가

#  ✅ PR포인트
- 적절하게 변수명이 사용되었는지
- 다양한 컴포넌트들이 제 기능을 구현하고 있는지
- 컴포넌트 분리의 단위가 적절한지

2023-10-29 09:57 UTC, Duckuism requested changes
호민님~! 기능 자체는 잘 구현하셨는데 함수형 컴포넌트를 사용하시기로 마음 먹으셨다면 전반적으로 사용하고 계시는 this의 사용을 제거할 필요가 있습니다.

class 컴포넌트에서는 해당 객체 인스턴스에 접근하여 특정 변수나 메서드의 key 값을 접근하기 위해 this를 불가피하게 사용해야하지만, 함수형 컴포넌트에서는 함수를 직접 export 하면 되기 때문에 this를 굳이 사용할 필요가 없어요.

제가 남긴 리뷰 참고하셔서 어떻게 개선할 수 있을 지 생각해봐주세요~! ㅎㅎ

2023-10-29 09:57 UTC, Duckuism commented on src/App.js
> +  initRouter(() => this.route());
```suggestion
  (this.route = () => {
    $EditorContainer.innerHTML = ``;
    const { pathname } = window.location;
    if (pathname === "/") {
      homePage.render();
    } else if (pathname.indexOf("/documents/") === 0) {
      const documentID = pathname.split("/").pop();
      editorPage.setState({ selectedID: documentID });
    }
  })();

  initRouter(this.route);
```

2023-10-29 09:57 UTC, Duckuism commented on src/App.js
> +  });
```
export default function HomePage({ $target }) {
  const $home = document.createElement("div");
  const $span = document.createElement("div");
  $span.innerHTML = `Hober's Notion`;

  $home.classList = "home-page";

  const $image = document.createElement("img");
  $image.src = "../img/notion.PNG";
  $home.appendChild($span);
  $span.appendChild($image);

  const render = () => $target.appendChild($home);

  return {
    render,
  };
}

```

```suggestion
  const homePage = HomePage({
    $target: $EditorContainer,
  });
```

클래스를 사용하지 않고 있다면 굳이 생성자 함수를 쓰지 않고도 구현이 가능하니 참고하세요

2023-10-29 09:57 UTC, Duckuism commented on src/App.js
> +  $documentListContainer.classList = "list-container";
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

![스크린샷 2023-10-29 오후 6 34 25](https://github.com/prgrms-fe-devcourse/FEDC5-5_Project_Notion_VanillaJS/assets/24688568/fd938858-41ee-4cca-854e-b92f27181e3d)

readonly 속성인데 직접 할당을 하면 안 되겠죠? ☺️

만약 클래스 이름을 동적으로 추가하고 싶으셨던 거라면 `$home.className = "home-page"`로 사용하거나, `$home.classList.add("home-page")`를 사용하시면 됩니다.

2023-10-29 09:57 UTC, Duckuism commented on src/page/ListPage.js
> +export default function ListPage({ $target, initialState }) {
호민님 여기는 코드 수정해서 리뷰 달까하다가... 직접 해보시는게 나을 것 같아 코멘트만 드립니다.

this를 사용하지 않고 구현할 수는 없을지 다시 한 번 살펴봐주세요.

2023-10-29 09:57 UTC, Duckuism commented on src/page/EditorPage.js
> +      const selectedDocument = await request(`/documents/${selectedID}`);
특정 document의 데이터를 가져오는 API 호출 코드가 EditorPage.js에도 있고 ListPage.js에도 있네요.
api 호출하는 코드들을 함수로 만들고 하나의 파일에 모아 export 한다면 다른 파일들에서 import해서 사용하고 중복 코드를 제거할 수 있겠죠?

2023-10-29 10:45 UTC, Duckuism reviewed
> 호민님 궁금하신 점 남겨주셨는데 이 부분 추가로 부연 설명 좀 해 주시겠어요~!?

각 컴포넌트별 상태관리를 어떻게 하는게 좋은지 > 어떤 방향과 어떤 방향이 고민되는지

> 컴포넌트간의 상호작용을 어떻게 하는지 잘 모르겠습니다.
예를들어 Editor에서 텍스트를 수정하는데 렌더링없이 List가 수정된다던지, Header에서 렌더링없이 텍스트가 변화하는 등

이게 어떤 케이스인지 모르겠는데, 스크린샷이나 화면녹화 첨부해주시면 좋겠습니다.

> contentEditable을 조합해 구현하는 방법을 익혀야 하는가 

이것도 어떤 걸 말씀하시는지 잘 모르겠는데 부연 설명좀 추가해주세요~!

2023-10-30 05:29 UTC, yjc2021 reviewed
호민님 과제하느라 고생하셨습니다! 호민님이 과제에 신경 많이 쓰신 만큼 컴포넌트를 분리 기준이나 각 컴포넌트에서 진행되는 상태 관리 및 rendering 로직이 깔끔하고 이해하기 쉬웠습니다 :)  저는 위에서 아래로 모든 로직을 주입하려고 해서 구현할 때 중복되는 렌더링도 있고 헷갈렸었는데 호민님 코드 보면서 많이 배웠습니다! 리뷰 내용은 수정사항이라기 보다 구현 스타일 비교 정도로 봐주시면 될 것 같아요! 수고하셨습니다 :)

2023-10-30 05:29 UTC, yjc2021 commented on src/page/ListPage.js
> +  this.fetchDocumentsList = async () => {
저도 호민님처럼 root documents get api를 여러번 호출하는 방식으로 document list를 최신화했는데 윤서님 코드를 보니까 App 실행 시 한번 호출하고 계속 내부 상태로 관리 하시더라구요. 저희도 해당 방식으로 연습해 봐도 좋을 것 같아요! :)

2023-10-30 05:29 UTC, yjc2021 commented on src/page/ListPage.js
> +  $docList.addEventListener("mouseover", (e) => {
저는 해당 기능을 css hover를 이용해서 구현했어요! 어떤 방식이 더 좋은지는 모르겠는데 같이 js event listener로 하는 방식과 css로 하는 방식의 내부 동작(?) 을 비교해봐도 좋은 공부가 될 것 같아요! :)

2023-10-30 05:29 UTC, yjc2021 commented on src/page/EditorPage.js
> +export default function EditorPage({ $target, initialState, onListRender }) {
호민님 별건 아니고 App에서 두 개의 div로 ListContainer랑 editorContainer를 분리하시고 해당 div안에 각각 다시 page용 div를 만드셨더라구요! 호민님이 page를 컴포넌트로 이미 구분하셔서 App에서 container div를 만들면 비슷한 용도의 div를 중복으로 만드는 것 같은 느낌이 개인적으로 들었습니다. 호민님은 어떤 의도였는지 궁금합니다 :)

2023-10-30 06:04 UTC, imssein reviewed
호민님 과제하느라 고생많았습니다😄
전체적으로 깔끔하게 잘 구현하신 것 같아요!
사이드바 트리 구현에서 isToplevel을 설정하여 상위 문서임을 알 수 있도록 구현하신 부분도 배워갑니다 : )
저희 노션 과제 얘기 많이했는데 앞으로 리팩토링도 같이 파이팅해봐요~!~~

2023-10-30 14:27 UTC, bgyoons reviewed
안녕하세요 호민님!
프로젝트 코드 잘 보았습니다 :)
컴포넌트 분리도 잘 되어있는 것 같고 가독성이 좋아서 저도 많이 배운 것 같아요!
렌더링 관련해서는 저도 모르는 지식이 많아 코멘트를 너무 한정적으로 달은 것이 죄송스럽네요 ..
다시 보면서 생각나는 것 있으면 코멘트를 추가해보도록 하겠습니다 :)
프로젝트하느라 고생 많으셨습니다!

2023-10-30 14:27 UTC, bgyoons commented on src/component/ListItem.js
> +export default class ListItem {
ListItem 컴포넌트만 클래스로 선언한 이유가 궁금합니다 :)

2023-10-30 14:27 UTC, bgyoons commented on src/component/ListItem.js
> +      $li.style.listStyle = "none";
listStyle 속성을 사용자의 동작에 따라 변경하는 것이 아니면 따로 style.css에 선언하는 것도 좋을 것 같습니다 :)

2023-10-30 14:27 UTC, bgyoons commented on src/page/ListPage.js
> +        $toggleButton.innerHTML = $toggleButton.innerHTML === "˅" ? "˃" : "˅";
지금은 로직이 그리 복잡하지 않지만 가독성 측면에서 `const isOpen = $toggleButton.innerHTML === "˅"` 이런 식으로 변수를 선언해서 `isOpen ? "˃" : "˅"`으로 해도 좋을 것 같다는 생각이 들었습니다 ㅎㅎ 참고만 해주세요!

2023-10-30 14:27 UTC, bgyoons commented on src/page/ListPage.js
> +        id !== window.location.pathname.split("/").pop()
`window.location.pathname.split("/").pop()` 부분도 코드가 너무 길고 pop된 요소가 뭐지?하는 생각이 드는 것 같아요!
App.js 44번째에 `const documentID = pathname.split("/").pop();`로 선언하신 것처럼 이것도 따로 변수를 선언해줘도 좋을 것 같다는 생각이 들었습니다 ㅎㅎ

2023-11-04 08:02 UTC, HoberMin commented on src/page/EditorPage.js
> +export default function EditorPage({ $target, initialState, onListRender }) {
구현하다보니 컴포넌트별로 div를 만들어줬는데 div가 겹치는부분이 몇군데 발생했네요 😂 리팩토링하면서 요소를 줄이는 방법으로 해봐야겠습니다.. !

2023-11-04 08:04 UTC, HoberMin commented on src/page/EditorPage.js
> +  const $eidtor = document.createElement("div");
코드를 보다보니 오타가 좀 많네요...하하 익스텐션 깔아보겠습니다 추천감사합니다 👍

2023-11-04 08:05 UTC, HoberMin commented on src/component/ListItem.js
> +export default class ListItem {
이부분도 수정했어야 했는데 컴포넌트별로 처음에 class로 구현을 진행하다가 너무 복잡해져서 다시 생성자 함수로 돌아오는 과정에서 남은 잔유물 같습니다.. 리팩토링하면서 함수형으로 바꾸겠습니다..! 별다른 이유가 없어요 ㅠ..ㅠ

2023-11-04 08:06 UTC, HoberMin commented on src/component/ListItem.js
> +      $li.style.listStyle = "none";
css부분이 확실하게 많이 약하다는게 느껴지네요 리팩토링할때 css부분도 정리 잘해서 고쳐보겠습니다

2024-01-22 09:26 UTC, closed without merging